'use strict';

const grpc = require('@grpc/grpc-js');
const { connect, signers } = require('@hyperledger/fabric-gateway');
const crypto = require('node:crypto');
const fs = require('node:fs');
const fsp = require('node:fs/promises');
const path = require('node:path');

// Paths point at the crypto material generated by fabric-samples/test-network's
// network.sh (organizations/peerOrganizations/...). FABRIC_SAMPLES_PATH lets this
// be overridden so the backend can run outside the fabric-samples checkout.
const FABRIC_SAMPLES_PATH = process.env.FABRIC_SAMPLES_PATH
    || path.resolve(__dirname, '../../../fabric-samples');

const ORG_CONFIG = {
    org1: {
        mspId: 'Org1MSP',
        domain: 'org1.example.com',
        peerEndpoint: 'localhost:7051',
        peerHostAlias: 'peer0.org1.example.com'
    },
    org2: {
        mspId: 'Org2MSP',
        domain: 'org2.example.com',
        peerEndpoint: 'localhost:9051',
        peerHostAlias: 'peer0.org2.example.com'
    }
};

const CHANNEL_NAME = process.env.FABRIC_CHANNEL || 'mychannel';
const CHAINCODE_NAME = process.env.FABRIC_CHAINCODE || 'rxguard';

async function newGrpcConnection(orgKey) {
    const org = ORG_CONFIG[orgKey];
    const orgPath = path.join(FABRIC_SAMPLES_PATH, 'test-network', 'organizations', 'peerOrganizations', org.domain);
    const tlsCertPath = path.join(orgPath, 'peers', org.peerHostAlias, 'tls', 'ca.crt');
    const tlsRootCert = await fsp.readFile(tlsCertPath);
    const tlsCredentials = grpc.credentials.createSsl(tlsRootCert);
    return new grpc.Client(org.peerEndpoint, tlsCredentials, {
        'grpc.ssl_target_name_override': org.peerHostAlias
    });
}

async function newIdentity(orgKey, userLabel = 'User1') {
    const org = ORG_CONFIG[orgKey];
    const orgPath = path.join(FABRIC_SAMPLES_PATH, 'test-network', 'organizations', 'peerOrganizations', org.domain);
    const certDir = path.join(orgPath, 'users', `${userLabel}@${org.domain}`, 'msp', 'signcerts');
    const files = await fsp.readdir(certDir);
    const certPath = path.join(certDir, files[0]);
    const credentials = await fsp.readFile(certPath);
    return { mspId: org.mspId, credentials };
}

async function newSigner(orgKey, userLabel = 'User1') {
    const org = ORG_CONFIG[orgKey];
    const orgPath = path.join(FABRIC_SAMPLES_PATH, 'test-network', 'organizations', 'peerOrganizations', org.domain);
    const keyDir = path.join(orgPath, 'users', `${userLabel}@${org.domain}`, 'msp', 'keystore');
    const files = await fsp.readdir(keyDir);
    const keyPath = path.join(keyDir, files[0]);
    const privateKeyPem = await fsp.readFile(keyPath);
    const privateKey = crypto.createPrivateKey(privateKeyPem);
    return signers.newPrivateKeySigner(privateKey);
}

/**
 * Opens a Fabric Gateway connection for the given role ("prescriber" -> org1,
 * "pharmacist" -> org2) and returns { gateway, network, contract, close }.
 * The caller is responsible for invoking close() once done.
 */
async function connectAs(orgKey, userLabel = 'User1') {
    const client = await newGrpcConnection(orgKey);
    const identity = await newIdentity(orgKey, userLabel);
    const signer = await newSigner(orgKey, userLabel);

    const gateway = connect({
        client,
        identity,
        signer,
        evaluateOptions: () => ({ deadline: Date.now() + 5000 }),
        endorseOptions: () => ({ deadline: Date.now() + 15000 }),
        submitOptions: () => ({ deadline: Date.now() + 5000 }),
        commitStatusOptions: () => ({ deadline: Date.now() + 60000 })
    });

    const network = gateway.getNetwork(CHANNEL_NAME);
    const contract = network.getContract(CHAINCODE_NAME);

    return {
        gateway,
        network,
        contract,
        close: () => {
            gateway.close();
            client.close();
        }
    };
}

module.exports = { connectAs, ORG_CONFIG, CHANNEL_NAME, CHAINCODE_NAME };
